kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: mem-traefik-scc
  annotations:
    kubernetes.io/description: mem-traefik-scc provides all features of the restricted SCC but allows users to run with any UID and any GID.
priority: 10
# Determine if any container in a pod can enable privileged mode. By default a container is not
# allowed to access any devices on the host, but a "privileged" container is given access to all
# devices on the host. This allows the container nearly all the same access as processes running on
# the host. This is useful for containers that want to use Linux capabilities like manipulating the
# network stack and accessing devices.
allowPrivilegedContainer: false
# Gate whether or not a user is allowed to set the security context of a container to
# allowPrivilegeEscalation=true. This defaults to allowed so as to not break setuid binaries.
# Setting it to false ensures that no child process of a container can gain more privileges than
# its parent.
allowPrivilegeEscalation: false
#
allowHostDirVolumePlugin: false
# Control whether the pod may use the node network namespace. Doing so gives the pod access to the
# loopback device, services listening on localhost, and could be used to snoop on network activity
# of other pods on the same node.
allowHostNetwork: false
# Provide a list of ranges of allowable ports in the host network namespace. Defined as a list of
# HostPortRange, with min(inclusive) and max(inclusive). Defaults to no allowed host ports.
allowHostPorts: false
# Control whether the pod containers can share the host process ID namespace. Note that when paired
# with ptrace this can be used to escalate privileges outside of the container (ptrace is forbidden
# by default).
allowHostPID: false
# Control whether the pod containers can share the host IPC namespace.
allowHostIPC: false
# To prevent processes from writing to the container's filesystem (processes can only write to
# volumes), set the container's securityContext.readOnlyRootFilesystem property to true. When you
# make the container's filesystem read-only, you will probably want to mount a volume in every
# directory the app writes.
readOnlyRootFilesystem: true
# To get a capabilities list, go to:
# https://man7.org/linux/man-pages/man7/capabilities.7.html
# To see a list of runtime privilege and Linux capabilities, go to:
# https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities
# Provide a list of capabilities that are allowed to be added to a container. The default set of
# capabilities are implicitly allowed. The empty set means that no additional capabilities may be
# added beyond the default set. * can be used to allow all capabilities.
allowedCapabilities: [
]
# The capabilities which are added to containers by default, in addition to the runtime defaults.
defaultAddCapabilities: [
  # Bind a socket to Internet domain privileged ports (port numbers less than 1024).
  NET_BIND_SERVICE
]
# The capabilities which must be dropped from containers. These capabilities are removed from the
# default set, and must not be added. Capabilities listed in requiredDropCapabilities must not be
# included in allowedCapabilities or defaultAddCapabilities.
requiredDropCapabilities: [
  ALL
]
# Control which user ID the containers are run with.
runAsUser:
  type: RunAsAny
  uid: 1122
#
fsGroup:
  type: RunAsAny
#
supplementalGroups:
  type: RunAsAny
#
seLinuxContext:
  type: MustRunAs
# The users and groups fields on the SCC control which users can access the SCC. All authenticated
# users are granted access to the Restricted SCC.
# system:serviceaccount:<serviceaccount_namespace>:<serviceaccount_name>
users: [
  system:serviceaccount:memories:mem-traefik-service-account
]
groups: [
  system:authenticated
]
# Provide a list of allowed volume types.
# Notes:
# (1) For backwards compatibility, the usage of allowHostDirVolumePlugin overrides settings in the
#     volumes field.
volumes: [
  configMap,
  downwardAPI,
  emptyDir,
  persistentVolumeClaim,
  projected,
  secret
]
