kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: mem-traefik-scc
  annotations:
    kubernetes.io/description: mem-traefik-scc provides all features of the restricted SCC but allows users to run with any UID and any GID.
priority: 10
allowPrivilegedContainer: false
# Gate whether or not a user is allowed to set the security context of a container to
# allowPrivilegeEscalation=true. This defaults to allowed so as to not break setuid binaries.
# Setting it to false ensures that no child process of a container can gain more privileges than
# its parent.
allowPrivilegeEscalation: false
#
allowHostDirVolumePlugin: false
allowHostNetwork: false
allowHostPorts: false
allowHostPID: false
allowHostIPC: false
readOnlyRootFilesystem: true
# To get a capabilities list, go to:
# https://man7.org/linux/man-pages/man7/capabilities.7.html
# To see a list of runtime privilege and Linux capabilities, go to:
# https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities
# Provide a list of capabilities that are allowed to be added to a container. The default set of
# capabilities are implicitly allowed. The empty set means that no additional capabilities may be
# added beyond the default set. * can be used to allow all capabilities.
allowedCapabilities: [
]
# The capabilities which are added to containers by default, in addition to the runtime defaults.
defaultAddCapabilities: [
  # Bind a socket to Internet domain privileged ports (port numbers less than 1024).
  NET_BIND_SERVICE
]
# The capabilities which must be dropped from containers. These capabilities are removed from the
# default set, and must not be added. Capabilities listed in requiredDropCapabilities must not be
# included in allowedCapabilities or defaultAddCapabilities.
requiredDropCapabilities: [
  ALL
]
# Control which user ID the containers are run with.
runAsUser:
  # type: MustRunAsRange
  # type: MustRunAs
  type: RunAsAny
#
fsGroup:
  type: RunAsAny
  # type: MustRunAs
#
supplementalGroups:
  type: RunAsAny
#
seLinuxContext:
  type: MustRunAs
# The users and groups fields on the SCC control which users can access the SCC. All authenticated
# users are granted access to the Restricted SCC.
# system:serviceaccount:<serviceaccount_namespace>:<serviceaccount_name>
users: [
  system:serviceaccount:memories:mem-traefik-service-account
]
groups: [
  system:authenticated
]
# Provide a list of allowed volume types.
# Notes:
# (1) For backwards compatibility, the usage of allowHostDirVolumePlugin overrides settings in the
#     volumes field.
volumes: [
  configMap,
  downwardAPI,
  emptyDir,
  persistentVolumeClaim,
  projected,
  secret
]
