ingressRoute:
  dashboard:
    enabled: false
    # enabled: true
    # annotations: { traefik.ingress.kubernetes.io/router.tls: "true" }
ports:
  web:
    port: 8000
    expose: true
    exposedPort: 80
  websecure:
    port: 8443
    expose: true
    # exposedPort: 443
    exposedPort: 8443
  traefik:
    port: 9000
    # DO NOT expose the traefik port on production deployments. To access it from outside of the
    # cluster, use `kubectl port-forward` or create a secure ingress.
    # $ kubectl port-forward -n memories $(kubectl get pods -n memories --selector "app.kubernetes.io/name=traefik" --output=name) 9000:9000
    # From a browser, use http://127.0.0.1:9000/dashboard/ to see the Traefik dashboard; the trailing slash / in /dashboard/ is mandatory.
    expose: false
    # The exposed port for this service
    exposedPort: 9000
  metrics:
    port: 9100
    # See traefik.
    expose: false
    # The exposed port for this service
    exposedPort: 9100
additionalArguments:
  # For a list of all settings, go here
  # (https://doc.traefik.io/traefik/reference/static-configuration/cli/).
  - "--api=true"
  - "--api.dashboard=true"
  - "--api.insecure=true"
  - "--log=true"
  - "--log.level=INFO"
  - "--entrypoints.web.address=:80"
  # - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
  # - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
  - "--entrypoints.websecure.address=:8443"
  - "--providers.kubernetescrd=true"
  # - "--entrypoints.websecure.http.tls"
  # - "--providers.kubernetesIngress.ingressClass=traefik-cert-manager"
  # - "--ping"
  - "--metrics.prometheus=true"
# Set the container security context
# To run the container with ports below 1024 this will need to be adjust to run as root
securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  readOnlyRootFilesystem: true
  runAsGroup: 1100
  runAsNonRoot: false
  runAsUser: 0
podSecurityContext:
  fsGroup: 1100
